version: '3.8'

services:
  front-end:
    container_name: front-end
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - docker_network

networks:
  docker_network:
    external:
      name: custom_network