version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - docker_network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
volumes:
  postgres-data:

networks:
  docker_network:
    name: custom_network