version: '3.8'

services:
  back-end:
    container_name: back-end
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - docker_network

networks:
  docker_network:
    external:
      name: custom_network